languageCode = "en-us"
MetaDataFormat = "toml"
theme = "kbtheme"
publishdir = "public"

# If site servered from somewhere other than server root, canonification
# may be required for css to load properly.
canonifyurls = false



baseurl = "http://lisabrzozowski.com/"
title = "Lisa Brzozowski"

[params]
    SiteName = "Lisa Brzozowski"
    ArtistName = "Lisa Brzozowski"
    FeedbackUrl = ""
